import os
import sys
import random
import datetime as dt
import pandas as pd
import numpy as np
import warnings

import src.streamlit_executive_data_loader as data_loader
from src.streamlit_executive_data_loader import (
    get_kpi_annual_actual_series,
    get_kpi_monthly_actual_table,
    get_period_type,
    get_kpi_annual_forecast_series,
    lookup_forecast_record,
    lookup_forecast_warning,
    lookup_forecast_eligibility,
    get_forecast_capability_notice,
    FORECAST_HORIZON_START_MONTH,
    FORECAST_HORIZON_END_MONTH,
)
from src.streamlit_executive_narrative_engine import build_executive_narrative
from src.streamlit_executive_priority_engine import select_primary_package
from src.streamlit_executive_visualisation_engine import render_kpi_trend_chart
from src.genai_provenance_badge import (
    is_hy3_live,
    render_hy3_badge_html,
    render_hy3_caption_html,
    render_hy3_provenance_html,
    BADGE_LABEL as _HY3_BADGE_LABEL,
    KPI_PROVENANCE_CAPTION as _HY3_KPI_CAPTION,
    CS_PROVENANCE_CAPTION as _HY3_CS_CAPTION,
)

# Note: causality is not confirmed in any narrative generated by this module.
# Decision support only; authorised management review required for final action.

# Enable logging
_log = None

_PRESSURE_STAGES = [
    {"label": "Trigger", "description": "Initial indicator identified."},
    {"label": "Escalation", "description": "Threshold crossed; management alert."},
    {"label": "Resolution", "description": "Action taken or monitoring confirmed."},
]


def is_all_departments(department_id):
    """Check if the selected department is the 'All Departments' aggregate."""
    return str(department_id).upper() in ("ALL", "ALL DEPARTMENTS", "")


# ───────────────────────────────────────────────────────────────────────────
# KPI STATUS EVALUATION (authoritative, value-driven, decoupled from package risk)
# ───────────────────────────────────────────────────────────────────────────

def load_kpi_threshold_config():
    """Load KPI thresholds from authoritative config with dual-sided boundaries."""
    path = os.path.join("config", "kpi_threshold_config.csv")
    if not os.path.isfile(path):
        return {}
    try:
        df = pd.read_csv(path)
        config = {}
        for _, row in df.iterrows():
            kpi_id = str(row.get("kpi_id", "")).strip()
            if not kpi_id:
                continue
            directionality_raw = str(row.get("directionality", "")).strip().lower()
            if directionality_raw == "higher is better":
                directionality = "HIGHER_IS_BETTER"
            elif directionality_raw == "lower is better":
                directionality = "LOWER_IS_BETTER"
            elif directionality_raw == "context-sensitive":
                directionality = "TARGET_BAND"
            else:
                directionality = _correct_directionality(kpi_id, directionality_raw)

            def _f(val):
                if pd.isna(val) or val == "" or val == "nan":
                    return None
                try:
                    return float(val)
                except Exception:
                    return None

            config[kpi_id] = {
                "kpi_name": str(row.get("kpi_name", "")),
                "directionality": directionality,
                "lower_red_boundary": _f(row.get("lower_red_boundary")),
                "lower_amber_boundary": _f(row.get("lower_amber_boundary")),
                "green_lower_boundary": _f(row.get("green_lower_boundary")),
                "green_upper_boundary": _f(row.get("green_upper_boundary")),
                "upper_amber_boundary": _f(row.get("upper_amber_boundary")),
                "upper_red_boundary": _f(row.get("upper_red_boundary")),
                "unit": str(row.get("unit", "")),
                "approval_status": str(row.get("approval_status", "Provisional")),
                "effective_date": str(row.get("effective_date", "")),
                "threshold_is_provisional": bool(row.get("threshold_is_provisional", False)),
                "conditions_of_approval": str(row.get("conditions_of_approval", "")) if not pd.isna(row.get("conditions_of_approval")) else "",
            }
        return config
    except Exception as e:
        if _log:
            _log.warning(f"Threshold config load failed: {e}")
        return {}


def _correct_directionality(kpi_id, raw):
    """Return the clinically correct directionality regardless of config label errors."""
    mapping = {
        "kpi_001": "HIGHER_IS_BETTER",
        "kpi_002": "LOWER_IS_BETTER",
        "kpi_003": "TARGET_BAND",
        "kpi_004": "LOWER_IS_BETTER",
        "kpi_005": "LOWER_IS_BETTER",
        "kpi_006": "HIGHER_IS_BETTER",
    }
    return mapping.get(kpi_id, raw.upper() if raw else "LOWER_IS_BETTER")


def normalize_kpi_value_and_thresholds(value, thresholds, unit=None):
    """
    Normalize KPI value and thresholds to a canonical scale.

    Canonical percentage scale: 0-100 (percentage points).
    A value of 84.6 represents 84.6 percent.
    A threshold of 15.0012 represents 15.0012 percent.

    If the unit is 'Percent' and a scale mismatch is detected between
    value and thresholds (e.g., value=0.154 vs threshold=15.4),
    the value is scaled to percentage points.

    Returns:
        dict with keys:
            value: normalized value
            thresholds: dict of normalized threshold values
            canonical_scale: "0-100" for Percent, otherwise "raw"
            scale_adjusted: bool indicating whether scaling was applied
    """
    normalized_value = value
    normalized_thresholds = dict(thresholds) if thresholds else {}
    scale_adjusted = False
    canonical_scale = "raw"

    if unit and "percent" in str(unit).lower():
        canonical_scale = "0-100"

        # Detect if value is in fraction scale (0-1) while thresholds are in percentage points (0-100)
        if value is not None and isinstance(value, (int, float)):
            thr_values = [
                v
                for v in normalized_thresholds.values()
                if v is not None and isinstance(v, (int, float))
            ]
            if thr_values:
                value_is_fraction = 0 < abs(value) < 1
                thresholds_are_points = all(abs(v) >= 1 for v in thr_values)
                if value_is_fraction and thresholds_are_points:
                    normalized_value = value * 100
                    scale_adjusted = True
                elif not value_is_fraction and all(0 < abs(v) < 1 for v in thr_values):
                    for k, v in normalized_thresholds.items():
                        if v is not None and isinstance(v, (int, float)) and 0 < abs(v) < 1:
                            normalized_thresholds[k] = v * 100
                    scale_adjusted = True

    return {
        "value": normalized_value,
        "thresholds": normalized_thresholds,
        "canonical_scale": canonical_scale,
        "scale_adjusted": scale_adjusted,
    }


def evaluate_kpi_status(
    kpi_id,
    value,
    lower_red_boundary=None,
    lower_amber_boundary=None,
    green_lower_boundary=None,
    green_upper_boundary=None,
    upper_amber_boundary=None,
    upper_red_boundary=None,
    directionality=None,
    unit=None,
    approval_status=None,
    effective_date=None,
):
    """
    Authoritative KPI status evaluation using dual-sided boundary thresholds.

    Returns dict with:
        status: one of "Green", "Amber", "Red", "Monitoring", "Not Assessable"
        status_text: "Acceptable", "Warning", "Critical", "Monitoring", "Not Assessable"
        border_colour: "green", "amber", "red", "blue", "grey"
        severity_score: float for ranking (Red=3, Amber=2, Green=1, Monitoring=0, Not Assessable=0)
        breach_magnitude: float (0 if Green/Monitoring/Not Assessable)
        status_meta: str explaining the rule source used
    """
    result = {
        "status": "Monitoring",
        "status_text": "Monitoring",
        "border_colour": "blue",
        "severity_score": 0.0,
        "breach_magnitude": 0.0,
        "status_meta": "Status cannot be determined",
    }

    if not isinstance(value, (int, float)) or pd.isna(value):
        return result

    # Normalize value and thresholds to canonical scale
    thresholds = {
        "lower_red": lower_red_boundary,
        "lower_amber": lower_amber_boundary,
        "green_lower": green_lower_boundary,
        "green_upper": green_upper_boundary,
        "upper_amber": upper_amber_boundary,
        "upper_red": upper_red_boundary,
    }
    normalized = normalize_kpi_value_and_thresholds(value, thresholds, unit)
    value = normalized["value"]
    t = normalized["thresholds"]

    def _to_float(x):
        if x is None or (isinstance(x, str) and str(x).strip() == ""):
            return None
        try:
            return float(x)
        except (ValueError, TypeError):
            return None

    lower_red = _to_float(t.get("lower_red"))
    lower_amber = _to_float(t.get("lower_amber"))
    green_lower = _to_float(t.get("green_lower"))
    green_upper = _to_float(t.get("green_upper"))
    upper_amber = _to_float(t.get("upper_amber"))
    upper_red = _to_float(t.get("upper_red"))

    # Missing or invalid threshold configuration must not default silently to Green
    all_thresholds = [lower_red, lower_amber, green_lower, green_upper, upper_amber, upper_red]
    if all(v is None for v in all_thresholds):
        result["status"] = "Not Assessable"
        result["status_text"] = "Not Assessable"
        result["border_colour"] = "grey"
        result["severity_score"] = 0.0
        result["status_meta"] = "Threshold Configuration Required"
        return result

    direction = (directionality or "LOWER_IS_BETTER").upper()

    # Identify provisional thresholds in status_meta
    provisional = ""
    if approval_status and str(approval_status).lower() in ("draft", "provisional"):
        provisional = f" [Provisional threshold, effective {effective_date}]"

    def _dist_to_boundary(val, boundary):
        if boundary is None or boundary == 0:
            return abs(val - boundary) if boundary is not None else 0
        return abs(val - boundary) / abs(boundary)

    if direction == "HIGHER_IS_BETTER":
        # Higher values are better.
        # Red: value <= lower_red (critically low)
        # Amber: lower_red < value < lower_amber (below warning)
        # Green: value >= green_lower (acceptable)
        green_bound = green_lower if green_lower is not None else (lower_amber if lower_amber is not None else None)
        amber_bound = lower_amber if lower_amber is not None else green_bound
        red_bound = lower_red

        if red_bound is not None and value <= red_bound:
            result["status"] = "Red"
            result["status_text"] = "Critical"
            result["border_colour"] = "red"
            result["severity_score"] = 3.0
            result["breach_magnitude"] = _dist_to_boundary(value, red_bound)
            result["status_meta"] = f"Below critical threshold ({red_bound}){provisional}"
        elif amber_bound is not None and value < amber_bound:
            result["status"] = "Amber"
            result["status_text"] = "Warning"
            result["border_colour"] = "amber"
            result["severity_score"] = 2.0
            result["breach_magnitude"] = _dist_to_boundary(value, amber_bound)
            result["status_meta"] = f"Below warning threshold ({amber_bound}){provisional}"
        elif green_bound is not None and value >= green_bound:
            result["status"] = "Green"
            result["status_text"] = "Acceptable"
            result["border_colour"] = "green"
            result["severity_score"] = 1.0
            result["status_meta"] = f"Above green threshold ({green_bound}){provisional}"
        elif green_upper is not None and value <= green_upper:
            result["status"] = "Green"
            result["status_text"] = "Acceptable"
            result["border_colour"] = "green"
            result["severity_score"] = 1.0
            result["status_meta"] = f"Within green upper bound ({green_upper}){provisional}"
        else:
            result["status"] = "Green"
            result["status_text"] = "Acceptable"
            result["border_colour"] = "green"
            result["severity_score"] = 1.0
            result["status_meta"] = f"No threshold exceeded{provisional}"

    elif direction == "LOWER_IS_BETTER":
        # Lower values are better.
        # Red: value >= upper_red (critically high)
        # Amber: value > green_upper (above green band, below critical)
        # Green: value <= green_upper (acceptable)
        green_bound = green_upper if green_upper is not None else (upper_amber if upper_amber is not None else None)
        red_bound = upper_red

        if red_bound is not None and value >= red_bound:
            result["status"] = "Red"
            result["status_text"] = "Critical"
            result["border_colour"] = "red"
            result["severity_score"] = 3.0
            result["breach_magnitude"] = _dist_to_boundary(value, red_bound)
            result["status_meta"] = f"Above critical threshold ({red_bound}){provisional}"
        elif green_bound is not None and value > green_bound:
            result["status"] = "Amber"
            result["status_text"] = "Warning"
            result["border_colour"] = "amber"
            result["severity_score"] = 2.0
            result["breach_magnitude"] = _dist_to_boundary(value, green_bound)
            result["status_meta"] = f"Above warning threshold ({green_bound}){provisional}"
        elif green_bound is not None and value <= green_bound:
            result["status"] = "Green"
            result["status_text"] = "Acceptable"
            result["border_colour"] = "green"
            result["severity_score"] = 1.0
            result["status_meta"] = f"Below green threshold ({green_bound}){provisional}"
        elif green_lower is not None and value >= green_lower:
            result["status"] = "Green"
            result["status_text"] = "Acceptable"
            result["border_colour"] = "green"
            result["severity_score"] = 1.0
            result["status_meta"] = f"Above green lower bound ({green_lower}){provisional}"
        else:
            result["status"] = "Green"
            result["status_text"] = "Acceptable"
            result["border_colour"] = "green"
            result["severity_score"] = 1.0
            result["status_meta"] = f"No threshold exceeded{provisional}"

    elif direction == "TARGET_BAND":
        # Target band: values inside green_lower..green_upper are Green.
        # Values outside the band but within red boundaries are Amber.
        # Values beyond red boundaries are Red.
        if lower_red is not None and value <= lower_red:
            result["status"] = "Red"
            result["status_text"] = "Critical"
            result["border_colour"] = "red"
            result["severity_score"] = 3.0
            result["breach_magnitude"] = _dist_to_boundary(value, lower_red)
            result["status_meta"] = f"Below critical lower bound ({lower_red}){provisional}"
        elif upper_red is not None and value >= upper_red:
            result["status"] = "Red"
            result["status_text"] = "Critical"
            result["border_colour"] = "red"
            result["severity_score"] = 3.0
            result["breach_magnitude"] = _dist_to_boundary(value, upper_red)
            result["status_meta"] = f"Above critical upper bound ({upper_red}){provisional}"
        elif green_lower is not None and value < green_lower:
            result["status"] = "Amber"
            result["status_text"] = "Warning"
            result["border_colour"] = "amber"
            result["severity_score"] = 2.0
            result["breach_magnitude"] = _dist_to_boundary(value, green_lower)
            result["status_meta"] = f"Below green lower bound ({green_lower}){provisional}"
        elif green_upper is not None and value > green_upper:
            result["status"] = "Amber"
            result["status_text"] = "Warning"
            result["border_colour"] = "amber"
            result["severity_score"] = 2.0
            result["breach_magnitude"] = _dist_to_boundary(value, green_upper)
            result["status_meta"] = f"Above green upper bound ({green_upper}){provisional}"
        else:
            result["status"] = "Green"
            result["status_text"] = "Acceptable"
            result["border_colour"] = "green"
            result["severity_score"] = 1.0
            result["status_meta"] = f"Within target band{provisional}"

    else:
        result["status"] = "Monitoring"
        result["status_text"] = "Monitoring"
        result["border_colour"] = "blue"
        result["severity_score"] = 0.0
        result["status_meta"] = "Unknown directionality"

    return result


# ───────────────────────────────────────────────────────────────────────────
# DOMINANT ISSUE SELECTION (transparent, all six KPIs eligible)
# ───────────────────────────────────────────────────────────────────────────

def select_dominant_issue(kpi_statuses, kpi_trends=None):
    """
    Select dominant issue from evaluated KPI statuses.

    kpi_statuses: dict of kpi_id -> evaluate_kpi_status result dict
    kpi_trends: optional dict of kpi_id -> trend score (e.g. recent slope)

    Returns dict with:
        dominant_kpi_id: str or None
        dominant_kpi_name: str or None
        dominant_status: str or None
        ranking: list of dicts sorted by priority
    """
    if not kpi_statuses:
        return {"dominant_kpi_id": None, "dominant_kpi_name": None, "dominant_status": None, "ranking": []}

    kpi_names = {
        "kpi_001": "Staffing Level",
        "kpi_002": "Staff Absenteeism Rate",
        "kpi_003": "Bed Occupancy Rate",
        "kpi_004": "Average Patient Waiting Time",
        "kpi_005": "Patient Complaint Rate",
        "kpi_006": "Patient Satisfaction Score",
    }

    rows = []
    for kpi_id, status_info in kpi_statuses.items():
        severity = status_info.get("severity_score", 0)
        breach = status_info.get("breach_magnitude", 0)
        trend = kpi_trends.get(kpi_id, 0) if kpi_trends else 0

        # Only amber/red KPIs can be dominant; severity >= 2
        if severity < 2:
            continue

        # Composite score: severity (3x) + breach magnitude (1x) + trend (0.5x)
        composite = (severity * 3.0) + (breach * 1.0) + (abs(trend) * 0.5)

        rows.append({
            "kpi_id": kpi_id,
            "kpi_name": kpi_names.get(kpi_id, kpi_id),
            "severity_score": severity,
            "breach_magnitude": breach,
            "trend_score": trend,
            "composite_score": composite,
            "status": status_info.get("status", "Monitoring"),
        })

    if not rows:
        return {"dominant_kpi_id": None, "dominant_kpi_name": None, "dominant_status": None, "ranking": []}

    rows.sort(key=lambda x: x["composite_score"], reverse=True)
    top = rows[0]
    return {
        "dominant_kpi_id": top["kpi_id"],
        "dominant_kpi_name": top["kpi_name"],
        "dominant_status": top["status"],
        "ranking": rows,
    }


# ───────────────────────────────────────────────────────────────────────────
# MANAGEMENT ACTION DIVERSITY (curated, KPI-specific, not package-inherited)
# ───────────────────────────────────────────────────────────────────────────

def _get_kpi_specific_management_action(kpi_id, status, kpi_value=None):
    """Return a management action description tailored to the dominant KPI."""
    actions = {
        "kpi_001": {
            "Red": "Critical staffing shortfall. Adjust roster; deploy temporary staffing; redistribute shifts; escalate to workforce planning.",
            "Amber": "Staffing below target. Review roster; consider temporary staff; optimise shift distribution.",
            "Green": "Staffing levels adequate. Continue routine monitoring.",
        },
        "kpi_002": {
            "Red": "High absenteeism. Review absence patterns; arrange relief staffing; assess roster resilience; escalate to HR.",
            "Amber": "Elevated absenteeism. Monitor trends; review absence reasons; prepare contingency cover.",
            "Green": "Absenteeism within acceptable range. Continue routine monitoring.",
        },
        "kpi_003": {
            "Red": "Critical bed occupancy. Coordinate discharge planning; escalate capacity; balance ward loads; review elective admissions.",
            "Amber": "High bed occupancy. Review discharge coordination; assess ward balancing; monitor elective scheduling.",
            "Green": "Bed occupancy within acceptable range. Continue routine monitoring.",
        },
        "kpi_004": {
            "Red": "Critical waiting times. Redesign queue flow; review triage; adjust demand-capacity balance; expand service slots.",
            "Amber": "Extended waiting times. Review queue design; assess triage; monitor demand patterns.",
            "Green": "Waiting times within acceptable range. Continue routine monitoring.",
        },
        "kpi_005": {
            "Red": "High complaint rate. Conduct complaint-theme review; initiate service recovery; communicate with affected patients; investigate processes.",
            "Amber": "Elevated complaint rate. Review complaint themes; assess service recovery needs; monitor trends.",
            "Green": "Complaint rate within acceptable range. Continue routine monitoring.",
        },
        "kpi_006": {
            "Red": "Low patient satisfaction. Launch experience review; implement quality intervention; improve communication; follow up patient feedback.",
            "Amber": "Declining satisfaction. Review experience drivers; assess quality gaps; plan targeted improvements.",
            "Green": "Patient satisfaction within acceptable range. Continue routine monitoring.",
        },
    }
    status_key = status if status in ("Red", "Amber", "Green") else "Green"
    return actions.get(kpi_id, {}).get(status_key, "Continue routine monitoring.")


def build_kpi_interpretation_card(card, threshold_cfg):
    """Build an HTML interpretation card for a single KPI (Actual-Only view)."""
    kpi_id = card.get("kpi_id", "")
    kpi_name = card.get("kpi_name", kpi_id)
    value = card.get("latest_value", "No data")
    unit = card.get("unit", "")

    cfg = threshold_cfg.get(kpi_id, {}) if threshold_cfg else {}

    # Determine status label and colour from card, preferring threshold_status
    status_label = card.get("threshold_status", "")
    if not status_label:
        status = card.get("status", "") or card.get("border_colour", "grey")
        if status in ("Red", "Amber", "Green"):
            status_label = status
        elif status in ("Not Assessable", "not assessable"):
            status_label = "Not Assessable"
        elif status in ("Insufficient Data", "insufficient data"):
            status_label = "Insufficient Data"
        elif status == "grey":
            status_label = "Insufficient Data"
        else:
            status_label = "Not Assessable"

    # Map status label to canonical colours
    if status_label in ("Red", "Amber", "Green"):
        status_colour = {"Red": "#C53030", "Amber": "#DD6B20", "Green": "#38A169"}.get(status_label, "#718096")
    elif status_label in ("Not Assessable", "Insufficient Data"):
        status_colour = "#718096"
    else:
        status_colour = "#718096"

    # Operational meaning and management implication based on status
    if status_label == "Insufficient Data":
        op_meaning = "A valid monthly result cannot be calculated from the available records for this department and period."
        mgmt_action = "Complete or validate the required source records before management assessment."
        badge = "ACTUAL"
    elif status_label == "Not Assessable":
        op_meaning = "A governed threshold could not be resolved for this KPI."
        mgmt_action = "Validate the threshold mapping before escalation."
        badge = "ACTUAL"
    else:
        op_meanings = {
            "kpi_001": {"Red": "Critical staffing shortfall risking service continuity.", "Amber": "Staffing below optimal levels; monitoring required.", "Green": "Adequate staffing for current demand."},
            "kpi_002": {"Red": "Absenteeism critically high; immediate cover needed.", "Amber": "Absenteeism elevated; review patterns.", "Green": "Absenteeism within normal range."},
            "kpi_003": {"Red": "Bed occupancy critical; capacity breach imminent.", "Amber": "High bed occupancy; discharge planning needed.", "Green": "Bed occupancy within target range."},
            "kpi_004": {"Red": "Waiting times critical; patient safety risk.", "Amber": "Waiting times extended; queue review needed.", "Green": "Waiting times within acceptable range."},
            "kpi_005": {"Red": "Complaint rate high; service recovery required.", "Amber": "Complaint rate elevated; investigate themes.", "Green": "Complaint rate within acceptable range."},
            "kpi_006": {"Red": "Patient satisfaction critically low.", "Amber": "Patient satisfaction declining; review drivers.", "Green": "Patient satisfaction within acceptable range."},
        }
        # Map display status to op_meaning keys
        status_map = {"Critical": "Red", "Warning": "Amber", "Acceptable": "Green"}
        mapped_status = status_map.get(status_label, status_label)
        op_meaning = op_meanings.get(kpi_id, {}).get(mapped_status, "Continue routine monitoring.")
        mgmt_action = _get_kpi_specific_management_action(kpi_id, mapped_status)
        badge = "ACTUAL"

    # Build value display line
    if status_label == "Insufficient Data":
        value_line = f"<span style='color:#718096;'>Insufficient Data</span>"
    else:
        value_line = f"<span style='font-weight:600;'>{value}{unit}</span> <span style='color:{status_colour};font-weight:600;'>({status_label})</span>"

    html = (
        f"<div style='padding:10px;border-radius:6px;border-left:4px solid {status_colour};background:#F5F7FA;'>"
        f"<div style='font-size:10px;font-weight:700;color:#4A5568;margin-bottom:2px;'>"
        f"<span style='background:#EDF2F7;padding:2px 6px;border-radius:4px;'>{badge}</span> {kpi_name}</div>"
        f"<div style='font-size:12px;margin-bottom:4px;'>{value_line}</div>"
        f"<div style='font-size:11px;color:#4A5568;margin-bottom:4px;'><strong>Operational meaning:</strong> {op_meaning}</div>"
        f"<div style='font-size:11px;color:#1565C0;'><strong>Management implication:</strong> {mgmt_action}</div>"
        f"</div>"
    )
    return html


def build_forecast_interpretation_card(card, ai_interpretation=None):
    """Build a forward-looking interpretation card for a forecast-month KPI.

    Parameters
    ----------
    card: dict
        KPI card produced by ``build_kpi_cards``.
    ai_interpretation: dict, optional
        Result from ``AIKPIGraphSynthesisService.synthesize``.
        If provided and status == "OK", shows AI-ASSISTED badge
        and AI-generated interpretation.
        If missing or status != "OK", shows deterministic fallback.
    """
    kpi_id = card.get("kpi_id", "")
    kpi_name = card.get("kpi_name", kpi_id)
    unit = card.get("unit", "")
    status_label = card.get("threshold_status", "Monitoring")
    warning_level = str(card.get("warning_level", "Monitoring") or "Monitoring").strip()
    quality = str(card.get("forecast_quality", "") or "").strip()
    point = card.get("point_forecast")
    expected_change = str(card.get("expected_status_change", "") or "").strip()

    # Map status -> colour
    if status_label == "Critical":
        status_colour = "#C53030"
    elif status_label == "Warning":
        status_colour = "#DD6B20"
    elif status_label == "Acceptable":
        status_colour = "#38A169"
    else:
        status_colour = "#718096"

    # ── Forecast unavailable card (ineligible / missing record) ────────
    if card.get("forecast_unavailable") or point is None:
        limitation = card.get("forecast_limitation", "Forecast not generated for this combination.")
        html = (
            f"<div style='padding:10px;border-radius:6px;border-left:4px solid #718096;background:#F5F7FA;'>"
            f"<div style='font-size:10px;font-weight:700;color:#4A5568;margin-bottom:4px;'>"
            f"<span style='background:#EDF2F7;padding:2px 6px;border-radius:4px;'>FORECAST</span> {kpi_name}</div>"
            f"<div style='font-size:12px;margin-bottom:4px;font-weight:600;color:#718096;'>Forecast Not Available</div>"
            f"<div style='font-size:11px;color:#4A5568;margin-bottom:2px;'><strong>Reason:</strong> {limitation}</div>"
            f"</div>"
        )
        return html

    # ── Governed header (always visible) ───────────────────────────────
    value = card.get("latest_value", "N/A")
    header_html = (
        f"<div style='font-size:10px;font-weight:700;color:#4A5568;margin-bottom:4px;'>"
        f"<span style='background:#EDF2F7;padding:2px 6px;border-radius:4px;'>FORECAST</span> {kpi_name}</div>"
        f"<div style='font-size:12px;margin-bottom:2px;'>"
        f"<span style='font-weight:600;'>{format_unit_value(value, unit)}</span> "
        f"<span style='color:{status_colour};font-weight:600;'>({status_label})</span></div>"
    )

    # ── AI interpretation or deterministic fallback ────────────────────
    # Use the shared provenance helper as the single source of truth for
    # "this came from live Hy3" gating. The badge + caption only render
    # when the synthesis result has status == "OK".
    ai_ok = is_hy3_live(ai_interpretation)

    if ai_ok:
        what = ai_interpretation.get("what_is_changing", "")
        why = ai_interpretation.get("why_it_matters", "")
        badge_html = render_hy3_badge_html()
        provenance_html = render_hy3_caption_html(scope="kpi")
    else:
        # Deterministic fallback (mirrors service fallback logic)
        what, why = _forecast_interpretation_fallback(card)
        badge_html = ""
        provenance_html = ""

    qa_html = ""
    if what or why:
        qa_html = (
            f"{badge_html}"
            f"<div style='font-size:11px;font-weight:700;color:#1B2A4A;margin-bottom:2px;'>"
            f"WHAT IS CHANGING?</div>"
            f"<div style='font-size:12px;color:#4A5568;line-height:1.45;margin-bottom:8px;'>"
            f"{what or 'Forecast trajectory is unchanged.'}</div>"
            f"<div style='font-size:11px;font-weight:700;color:#1B2A4A;margin-bottom:2px;'>"
            f"WHY DOES IT MATTER?</div>"
            f"<div style='font-size:12px;color:#4A5568;line-height:1.45;margin-bottom:8px;'>"
            f"{why or 'Continue routine monitoring.'}</div>"
            f"{provenance_html}"
        )

    # NOTE (UI-REMOVAL 2026-08-06):
    # The bottom "warning_level · confidence · transition" evidence strip
    # is no longer rendered in the visible card. Underlying fields
    # (warning_level, confidence, status transition) are still produced
    # by the analytics layer, are still part of the governed evidence /
    # AI evidence pack, and remain available for tests and future use.
    # The strip is intentionally hidden from end-user presentation per
    # the unified Hy3 provenance convention.

    html = (
        f"<div style='padding:10px;border-radius:6px;border-left:4px solid {status_colour};background:#F5F7FA;'>"
        f"{header_html}"
        f"{qa_html}"
        f"</div>"
    )
    return html


def _forecast_interpretation_fallback(card: dict) -> tuple:
    """Return deterministic (what, why) text for a forecast KPI.

    Mirrors the fallback logic in ``AIKPIGraphSynthesisService``
    so the UI is consistent whether the service is called inline
    or passed from the page layer.
    """
    period_type = card.get("period_type", "FORECAST")
    month = card.get("month")  # not stored in card; use selected context externally
    # Derive a month name from the card's annual_df if available
    annual_df = card.get("annual_df")
    forecast_month = "the forecast period"
    if annual_df is not None and not annual_df.empty:
        fc_rows = annual_df[annual_df.get("source_type", "") == "FORECAST"] if "source_type" in annual_df.columns else annual_df.iloc[-1:]
        if not fc_rows.empty:
            m = fc_rows.iloc[-1].get("month")
            if m is not None:
                month_names = [
                    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
                ]
                forecast_month = month_names[int(m) - 1]

    warning = str(card.get("warning_level", "Monitoring") or "Monitoring").strip()
    change = str(card.get("expected_status_change", "") or "").strip()

    if change:
        what = (
            f"The {forecast_month} forecast indicates performance "
            f"is expected to move from {change}."
        )
    else:
        what = (
            f"The {forecast_month} forecast indicates the current "
            f"trajectory is unchanged."
        )

    if warning and warning != "Monitoring":
        why = (
            f"A {warning} has been identified and warrants "
            f"continued management monitoring."
        )
    else:
        why = (
            "Current performance is within expected parameters and "
            "should continue to be monitored."
        )

    return what, why


def _map_quality_to_confidence_label(quality: str) -> str:
    """Map forecast quality label to a confidence label."""
    q = str(quality or "").strip().lower()
    if "high" in q:
        return "High Confidence"
    if "low" in q:
        return "Low Confidence"
    return "Moderate Confidence"


def _forecast_op_outlook(kpi_id: str, status_label: str, warning_level: str, expected_change: str) -> str:
    """Forward-looking operational outlook text for a forecast KPI."""
    severity = "high" if status_label == "Critical" else ("moderate" if status_label == "Warning" else "low")
    change = str(expected_change or "").lower()
    direction = "deterioration" if any(t in change for t in ("deteriorat", "worsen", "escalat")) else ("stable" if status_label == "Acceptable" else "potential change")
    return (
        f"This KPI is projected to enter a {severity}-severity band under the current trend "
        f"({direction}). The forecast is indicative and may shift as new evidence arrives."
    )


def _fmt(value):
    """Format a numeric value to one decimal place."""
    try:
        return f"{float(value):.1f}"
    except (TypeError, ValueError):
        return str(value)


# Clean unit suffix map for KPI value display.
# Keys are matched case-insensitively against the raw `unit` field from the
# KPI daily data (e.g. "Percent", "Minutes", "Score (1-5 scale)",
# "Complaints per 1000 encounters"). Values are the cleaned user-facing suffix
# appended to the numeric value.
_UNIT_SUFFIX_MAP = {
    "percent": "%",
    "%": "%",
    "minutes": " minutes",
    "score (1-5 scale)": "/5 Likert",
    "score (1-5)": "/5 Likert",
    "1-5 likert score": "/5 Likert",
    "1-5 likert": "/5 Likert",
    "likert": "/5 Likert",
    "complaints per 1000 encounters": " complaints per 1,000 encounters",
    "complaints per 1,000 encounters": " complaints per 1,000 encounters",
}


def format_unit_value(value, unit: str) -> str:
    """Render a KPI value with a clean user-facing unit suffix, e.g. '88.1%'.

    Always returns one decimal place for numeric inputs. Non-numeric inputs
    (e.g. "N/A", "No data", "Forecast Not Available") are returned as-is so
    callers can pass through missing-data markers without double-formatting.
    """
    if value is None:
        return "N/A"
    s = str(value).strip()
    if s == "" or s.lower() in ("n/a", "no data", "nan", "forecast not available", "insufficient data"):
        return s if s else "N/A"
    # Re-format numeric values to one decimal place; preserve pre-formatted strings
    try:
        v = float(s)
        v_str = f"{v:.1f}"
    except (TypeError, ValueError):
        v_str = s

    raw_unit = (unit or "").strip()
    if not raw_unit:
        return v_str
    suffix = _UNIT_SUFFIX_MAP.get(raw_unit.lower(), f" {raw_unit}")
    # Already starts with a space for some suffixes; for "%" and "/5 Likert" do
    # not add a leading space.
    if suffix.startswith(" ") or suffix.startswith("/"):
        return f"{v_str}{suffix}"
    return f"{v_str}{suffix}"


# ───────────────────────────────────────────────────────────────────────────
# OPERATIONAL STORY BUILDER
# ───────────────────────────────────────────────────────────────────────────

def _build_operational_pressure_story(primary_kpi_cards, primary_pkg, threshold_cfg):
    """
    Build a Connected Operational Situation story using the evaluated
    primary card statuses (not package-level risk inheritance).
    """
    story_blocks = []
    for card in primary_kpi_cards:
        kpi_name = card.get("kpi_name", "")
        status = card.get("threshold_status", "Monitoring")
        value = card.get("latest_value", "")
        units = card.get("unit", "")
        if status in ("Red", "Critical"):
            story_blocks.append(
                f'<li><strong>Red:</strong> {kpi_name} {value} {units} is in a critical state.</li>'
            )
        elif status in ("Amber", "Warning"):
            story_blocks.append(
                f'<li><strong>Amber:</strong> {kpi_name} {value} {units} is at warning level.</li>'
            )
        elif status in ("Green", "Acceptable"):
            story_blocks.append(
                f'<li><strong>Green:</strong> {kpi_name} {value} {units} is stable.</li>'
            )
        else:
            story_blocks.append(
                f'<li><strong>Monitoring:</strong> {kpi_name} {value} {units} is under observation.</li>'
            )

    if not story_blocks:
        return (
            '<div style="padding: 12px; border-radius: 4px; background: #f3f4f6; margin-top: 12px;">'
            '<p style="margin:0; color:#374151;">No material operational breach is identified for the selected department and period. Continue routine monitoring.</p>'
            '</div>'
        )

    story_html = (
        '<div style="padding: 12px; border-radius: 4px; background: #f3f4f6; margin-top: 12px;">'
        '<ul style="margin: 0; padding-left: 18px; color: #374151; font-size: 13px; line-height: 1.5;">'
        + "".join(story_blocks)
        + '</ul></div>'
    )
    return story_html


# ───────────────────────────────────────────────────────────────────────────
# NARRATIVE BUILDERS
# ───────────────────────────────────────────────────────────────────────────

def _build_executive_narrative_block(
    department_name,
    reporting_date,
    dominant_kpi_name,
    dominant_kpi_id,
    dominant_status,
    primary_kpi_cards,
    financial_block,
    selected_date,
):
    """Build a consistent executive narrative that reflects the actual dominant issue."""
    if not dominant_kpi_name or not dominant_status or dominant_status not in ("Red", "Amber"):
        return (
            f"No material operational breach is identified for {department_name} on {selected_date}. "
            "All monitored KPIs are within acceptable thresholds. Continue routine monitoring."
        )

    narrative = (
        f"For {department_name} on {selected_date}, the dominant issue is {dominant_kpi_name} ({dominant_status}). "
    )

    # Add supporting KPI context
    related_issues = []
    for card in primary_kpi_cards:
        s = card.get("threshold_status", "")
        if s in ("Red", "Amber") and card.get("kpi_name") != dominant_kpi_name:
            related_issues.append(f"{card.get('kpi_name')} ({s})")
    if related_issues:
        narrative += f"Supporting concerns: {', '.join(related_issues)}. "

    # Management action
    action = _get_kpi_specific_management_action(dominant_kpi_id, dominant_status)
    narrative += f"Recommended action: {action}"

    return narrative


# ───────────────────────────────────────────────────────────────────────────
# 5-PIECE HEADER
# ───────────────────────────────────────────────────────────────────────────

def _build_5_piece_header(department_name, selected_date, primary_pkg, all_risk):
    """Build the five-piece header for the Executive Overview page."""
    dept = department_name if department_name else "All Departments"
    date = str(selected_date) if selected_date else "Latest Available"
    risk = "Risk data unavailable"
    trend = "Stable"
    compliance = "Monitoring"

    if not all_risk.empty:
        latest = all_risk.sort_values("reporting_date").iloc[-1] if "reporting_date" in all_risk.columns else None
        if latest is not None:
            risk = latest.get("risk_tier", "Risk data unavailable")
            trend = latest.get("trend_direction", "Stable")
            compliance = latest.get("compliance_status", "Monitoring")

    if primary_pkg is not None:
        risk = primary_pkg.get("risk_tier", risk)
        trend = primary_pkg.get("trend_direction", trend)
        compliance = primary_pkg.get("compliance_status", compliance)

    return {
        "department": dept,
        "reporting_date": date,
        "risk_tier": risk,
        "trend_direction": trend,
        "compliance_status": compliance,
    }


# ───────────────────────────────────────────────────────────────────────────
# KPI CARD HELPER
# ───────────────────────────────────────────────────────────────────────────

def _build_all_kpi_cards(
    kpi_daily, kpi_dept, selected_date, pkg_date, primary_pkg, threshold_cfg,
    hospital_id="HOSP-001", year=2025, month=1,
    forecast_df=None,
    warning_df=None,
    eligibility_df=None,
):
    """Build all six KPI cards.

    For Jan-Jul (actual period): use canonical monthly actual table.
    For Aug-Dec (forecast period): use governed forecast point_forecast
    when eligible; mark as "Forecast Not Available" when ineligible.
    """
    cards = []
    monthly_table = get_kpi_monthly_actual_table(kpi_daily)
    period_type = get_period_type(year, month)

    for kpi_id in ["kpi_001", "kpi_002", "kpi_003", "kpi_004", "kpi_005", "kpi_006"]:
        cfg = threshold_cfg.get(kpi_id, {}) if threshold_cfg else {}
        kpi_name = cfg.get("kpi_name", kpi_id)
        unit = cfg.get("unit", "")

        # ── FORECAST branch (Aug-Dec, single-department) ───────────────────
        if period_type == "FORECAST":
            if kpi_dept == "ALL":
                # No governed All Departments aggregate forecast exists
                cards.append({
                    "kpi_id": kpi_id,
                    "kpi_name": kpi_name,
                    "latest_value": "Forecast Not Available",
                    "latest_value_raw": None,
                    "unit": unit if unit else "",
                    "threshold_status": "Not Assessable",
                    "border_colour": "grey",
                    "threshold_value": None,
                    "trend": None,
                    "date": None,
                    "severity_score": 0.0,
                    "period_type": "FORECAST",
                    "trend_df": pd.DataFrame(),
                    "annual_df": pd.DataFrame(),
                    "forecast_unavailable": True,
                    "forecast_limitation": (
                        "Forecasts are generated at department–KPI level and "
                        "no governed aggregate forecast has been approved."
                    ),
                    "warning_level": "Not Assessable",
                    "point_forecast": None,
                    "lower_bound": None,
                    "upper_bound": None,
                    "forecast_quality": "",
                })
                continue
            elig = lookup_forecast_eligibility(eligibility_df, hospital_id, kpi_dept, kpi_id)
            eligibility_status = elig.get("eligibility_status", "")
            if eligibility_status == "ELIGIBLE":
                fc_rec = lookup_forecast_record(forecast_df, hospital_id, kpi_dept, kpi_id, year, month)
                warn_rec = lookup_forecast_warning(warning_df, hospital_id, kpi_dept, kpi_id, year, month)
                if fc_rec:
                    card = _build_forecast_kpi_card(
                        kpi_id=kpi_id,
                        kpi_name=kpi_name,
                        unit=unit,
                        forecast_record=fc_rec,
                        warning_record=warn_rec,
                        threshold_cfg=cfg,
                        hospital_id=hospital_id,
                        department_code=kpi_dept,
                        year=year,
                        month=month,
                        kpi_daily=kpi_daily,
                    )
                    cards.append(card)
                    continue
            # Ineligible or missing record -> Forecast Not Available
            cards.append(_build_unavailable_forecast_card(
                kpi_id=kpi_id, kpi_name=kpi_name, unit=unit,
                limitation=elig.get("limitation", "Forecast not generated for this combination."),
            ))
            continue

        # ── ACTUAL branch (Jan-Jul, any department) ─────────────────────────
        monthly_value = None
        valid_obs = None
        first_date = None
        last_date = None

        if not monthly_table.empty:
            mask = (
                (monthly_table["kpi_id"] == kpi_id)
                & (monthly_table["hospital"] == hospital_id)
                & (monthly_table["year"] == year)
                & (monthly_table["month"] == month)
            )
            if kpi_dept != "ALL":
                mask = mask & (monthly_table["department_code"] == kpi_dept)
            rows = monthly_table[mask]
            if not rows.empty:
                if kpi_dept == "ALL":
                    monthly_value = rows["monthly_actual_value"].mean()
                else:
                    monthly_value = rows.iloc[0].get("monthly_actual_value")
                unit = rows.iloc[0].get("unit", unit)
                valid_obs = rows.iloc[0].get("valid_observation_count")
                first_date = rows.iloc[0].get("first_date")
                last_date = rows.iloc[0].get("last_date")

        # No valid monthly value -> Insufficient Data
        if monthly_value is None or pd.isna(monthly_value):
            cards.append({
                "kpi_id": kpi_id,
                "kpi_name": kpi_name,
                "latest_value": "Insufficient Data",
                "latest_value_raw": None,
                "unit": unit if unit else "",
                "threshold_status": "Insufficient Data",
                "border_colour": "grey",
                "threshold_value": None,
                "trend": None,
                "date": None,
                "severity_score": 0.0,
                "period_type": "ACTUAL",
                "trend_df": pd.DataFrame(),
                "annual_df": pd.DataFrame(),
                "valid_observation_count": valid_obs,
                "first_date": first_date,
                "last_date": last_date,
            })
            continue

        # Evaluate status from thresholds
        status_result = evaluate_kpi_status(
            kpi_id=kpi_id,
            value=monthly_value,
            lower_red_boundary=cfg.get("lower_red_boundary"),
            lower_amber_boundary=cfg.get("lower_amber_boundary"),
            green_lower_boundary=cfg.get("green_lower_boundary"),
            green_upper_boundary=cfg.get("green_upper_boundary"),
            upper_amber_boundary=cfg.get("upper_amber_boundary"),
            upper_red_boundary=cfg.get("upper_red_boundary"),
            directionality=cfg.get("directionality"),
            unit=cfg.get("unit"),
            approval_status=cfg.get("approval_status"),
            effective_date=cfg.get("effective_date"),
        )

        # Build trend_df for the chart (last 30 days)
        trend_df = pd.DataFrame()
        if kpi_daily is not None and not kpi_daily.empty:
            trend_df = kpi_daily[
                (kpi_daily["kpi_id"] == kpi_id) & (kpi_daily["department_id"] == kpi_dept)
            ].copy()
        if not trend_df.empty:
            trend_df["reporting_date"] = pd.to_datetime(trend_df["reporting_date"])
            trend_df = trend_df.sort_values("reporting_date").tail(30)
            trend_df = trend_df[["reporting_date", "kpi_value"]]
        else:
            trend_df = pd.DataFrame()

        # Build annual actual series (Jan-Jul monthly averages) using canonical table
        annual_df = pd.DataFrame()
        if kpi_daily is not None and not kpi_daily.empty:
            annual_df = get_kpi_annual_actual_series(
                kpi_daily, hospital_id, kpi_dept, kpi_id, year
            )

        cards.append({
            "kpi_id": kpi_id,
            "kpi_name": kpi_name,
            "latest_value": f"{monthly_value:.{_precision(unit)}f}",
            "latest_value_raw": monthly_value,
            "unit": unit,
            "threshold_status": status_result["status_text"],
            "border_colour": status_result["border_colour"],
            "threshold_value": status_result["breach_magnitude"],
            "trend": None,
            "date": last_date,
            "severity_score": status_result["severity_score"],
            "period_type": "ACTUAL",
            "trend_df": trend_df,
            "annual_df": annual_df,
            "valid_observation_count": valid_obs,
            "first_date": first_date,
            "last_date": last_date,
        })

    return cards


def _build_forecast_kpi_card(
    kpi_id, kpi_name, unit, forecast_record, warning_record,
    threshold_cfg, hospital_id, department_code, year, month, kpi_daily,
):
    """Build a KPI card for an eligible forecast month (Aug-Dec)."""
    point_forecast = forecast_record.get("point_forecast")
    lower_bound = forecast_record.get("lower_bound")
    upper_bound = forecast_record.get("upper_bound")
    forecast_quality = forecast_record.get("forecast_quality", "")
    horizon = forecast_record.get("horizon_months_ahead", 0)

    # Map forecast_status -> colour/text for the card
    forecast_status = (warning_record or {}).get("forecast_status", "")
    expected_change = (warning_record or {}).get("expected_status_change", "")
    warning_level = (warning_record or {}).get("warning_level", "Monitoring")
    warning_reason = (warning_record or {}).get("warning_reason", "")
    suggested_action = (warning_record or {}).get("suggested_action_text", "")

    status_text, border_colour = _map_forecast_status(forecast_status, expected_change)

    # Severity score from warning level for ranking
    severity_score = _warning_severity_score(warning_level)

    # Build trend_df (no trend in forecast period)
    trend_df = pd.DataFrame()

    # Build annual_df: combine actual Jan-Jul + forecast Aug-Dec
    annual_df = pd.DataFrame()
    if kpi_daily is not None and not kpi_daily.empty:
        annual_df = get_kpi_annual_actual_series(
            kpi_daily, hospital_id, department_code, kpi_id, year
        )
    # Append the forecast row for the selected month to annual_df
    if annual_df.empty:
        annual_df = pd.DataFrame(columns=["kpi_id", "month", "monthly_value", "supported", "month_label"])
    fc_row = {
        "kpi_id": kpi_id,
        "month": month,
        "monthly_value": float(point_forecast) if point_forecast is not None and pd.notna(point_forecast) else None,
        "lower_value": float(lower_bound) if lower_bound is not None and pd.notna(lower_bound) else None,
        "upper_value": float(upper_bound) if upper_bound is not None and pd.notna(upper_bound) else None,
        "supported": True,
        "source_type": "FORECAST",
        "month_label": ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][month - 1],
    }
    annual_df = pd.concat([annual_df, pd.DataFrame([fc_row])], ignore_index=True)
    annual_df = annual_df.sort_values("month")

    card = {
        "kpi_id": kpi_id,
        "kpi_name": kpi_name,
        "latest_value": f"{float(point_forecast):.{_precision(unit)}f}" if point_forecast is not None and pd.notna(point_forecast) else "N/A",
        "latest_value_raw": float(point_forecast) if point_forecast is not None and pd.notna(point_forecast) else None,
        "unit": unit,
        "threshold_status": status_text,
        "border_colour": border_colour,
        "threshold_value": None,
        "trend": None,
        "date": None,
        "severity_score": severity_score,
        "period_type": "FORECAST",
        "trend_df": trend_df,
        "annual_df": annual_df,
        "valid_observation_count": None,
        "first_date": None,
        "last_date": None,
        "point_forecast": float(point_forecast) if point_forecast is not None and pd.notna(point_forecast) else None,
        "lower_bound": float(lower_bound) if lower_bound is not None and pd.notna(lower_bound) else None,
        "upper_bound": float(upper_bound) if upper_bound is not None and pd.notna(upper_bound) else None,
        "forecast_quality": forecast_quality,
        "warning_level": warning_level,
        "warning_reason": warning_reason,
        "expected_status_change": expected_change,
        "horizon_months_ahead": int(horizon) if horizon is not None and pd.notna(horizon) else None,
        "suggested_action": suggested_action,
        "forecast_id": forecast_record.get("forecast_id", ""),
        "selected_method": forecast_record.get("selected_method", ""),
        "threshold_config": threshold_cfg,
    }
    return card


def _build_unavailable_forecast_card(kpi_id, kpi_name, unit, limitation):
    """Build a KPI card for an ineligible forecast month."""
    return {
        "kpi_id": kpi_id,
        "kpi_name": kpi_name,
        "latest_value": "Forecast Not Available",
        "latest_value_raw": None,
        "unit": unit if unit else "",
        "threshold_status": "Not Assessable",
        "border_colour": "grey",
        "threshold_value": None,
        "trend": None,
        "date": None,
        "severity_score": 0.0,
        "period_type": "FORECAST",
        "trend_df": pd.DataFrame(),
        "annual_df": pd.DataFrame(),
        "valid_observation_count": None,
        "first_date": None,
        "last_date": None,
        "point_forecast": None,
        "lower_bound": None,
        "upper_bound": None,
        "forecast_quality": "",
        "warning_level": "Not Assessable",
        "warning_reason": limitation,
        "expected_status_change": "",
        "horizon_months_ahead": None,
        "suggested_action": "",
        "forecast_unavailable": True,
        "forecast_limitation": limitation,
        "forecast_id": "",
        "selected_method": "",
    }


def _map_forecast_status(forecast_status: str, expected_change: str) -> tuple:
    """Map forecast_status -> (status_text, border_colour)."""
    s = str(forecast_status or "").strip().lower()
    if s == "red":
        return "Critical", "red"
    if s == "amber":
        return "Warning", "amber"
    if s == "green":
        return "Acceptable", "green"
    # Use expected_status_change if status missing
    e = str(expected_change or "").strip().lower()
    if "deteriorat" in e or "worsen" in e or "red" in e:
        return "Warning", "amber"
    return "Monitoring", "grey"


def _warning_severity_score(warning_level: str) -> float:
    """Severity score from warning level for primary KPI ranking."""
    w = str(warning_level or "").strip().lower()
    if "high early" in w:
        return 5.0
    if "escalating" in w:
        return 4.0
    if "emerging" in w:
        return 3.0
    if "monitoring" in w:
        return 1.0
    return 0.0


def _split_primary_and_supporting(all_cards):
    """Split six KPI cards into primary (3 highest severity) and supporting (3 remaining).

    Preserves operational order in the supporting row.
    """
    if not all_cards:
        return [], []

    # KPI operational order for tie-breaking and supporting row
    kpi_order = ["kpi_001", "kpi_002", "kpi_003", "kpi_004", "kpi_005", "kpi_006"]

    # Sort by severity descending, then by operational order ascending
    def _sort_key(card):
        kpi_id = card.get("kpi_id", "")
        severity = card.get("severity_score", 0)
        order_index = kpi_order.index(kpi_id) if kpi_id in kpi_order else 99
        return (-severity, order_index)

    sorted_cards = sorted(all_cards, key=_sort_key)
    primary = sorted_cards[:3]
    supporting = sorted(sorted_cards[3:], key=lambda c: kpi_order.index(c.get("kpi_id", "")) if c.get("kpi_id", "") in kpi_order else 99)
    return primary, supporting


def _precision(unit):
    return 1


def _card_border_colour(status):
    """Shared status-to-colour mapping."""
    s = str(status).lower()
    if s in ("green", "acceptable", "stable"):
        return "green"
    if s in ("amber", "warning", "watch"):
        return "amber"
    if s in ("red", "critical"):
        return "red"
    if s in ("monitoring", "informational"):
        return "blue"
    return "grey"


def _derive_operational_status_from_cards(cards):
    """Derive operational status from primary KPI cards using selected-month values."""
    if not cards:
        return "MONITORING"
    has_critical = any(c.get("severity_score", 0) >= 3.0 for c in cards)
    has_warning = any(c.get("severity_score", 0) >= 2.0 for c in cards)
    if has_critical:
        return "PRIORITY MANAGEMENT REVIEW"
    if has_warning:
        return "MANAGEMENT REVIEW REQUIRED"
    return "STABLE OPERATIONS"


# ───────────────────────────────────────────────────────────────────────────
# FINANCIAL BLOCK
# ───────────────────────────────────────────────────────────────────────────

def _build_financial_impact_block(
    primary_pkg,
    selected_date,
    financial_df,
    integrated_decision_df,
    selected_context=None,
):
    """Build financial impact block with State A (quantified) or State B (readiness).

    Returns a dict with:
        display_state: "QUANTIFIED" or "READINESS"
        text: plain text summary
        html: HTML rendering for the UI
        cost, benefit, net: numeric or None
        confidence, completeness: strings
        missing_inputs: list of strings
        next_step: string
        readiness_reasons: list of strings
        scenario_name: string or None
    """
    result = {
        "display_state": "READINESS",
        "text": "Financial estimate not available for the selected period.",
        "html": "",
        "cost": None,
        "benefit": None,
        "net": None,
        "confidence": "Not Assessable",
        "completeness": "Not Available",
        "missing_inputs": [],
        "next_step": "Validate financial assumptions before management comparison.",
        "readiness_reasons": [],
        "scenario_name": None,
    }

    ctx = selected_context or {}
    ctx_hospital = ctx.get("hospital_id", "")
    ctx_dept = ctx.get("department_id", "")
    ctx_year = ctx.get("selected_year")
    ctx_month = ctx.get("selected_month")

    if not primary_pkg or not primary_pkg.get("decision_package_id"):
        result["readiness_reasons"].append("No primary package selected for the selected context.")
        return result

    pkg_id = primary_pkg.get("decision_package_id", "")
    dept_id = primary_pkg.get("affected_department", primary_pkg.get("department_id", ""))

    # Helper to filter by selected context (hospital, department, year, month)
    def _filter_by_context(df, date_col="reporting_date"):
        if df is None or df.empty:
            return df
        matches = df.copy()
        # Filter by department_code
        if ctx_dept and ctx_dept != "ALL" and "department_id" in matches.columns:
            matches = matches[matches["department_id"] == ctx_dept]
        elif ctx_dept and ctx_dept != "ALL" and "affected_department" in matches.columns:
            matches = matches[matches["affected_department"] == ctx_dept]
        # Filter by year/month from date column
        if ctx_year is not None and ctx_month is not None and date_col in matches.columns:
            matches[date_col] = pd.to_datetime(matches[date_col], errors="coerce")
            matches = matches[
                (matches[date_col].dt.year == ctx_year) &
                (matches[date_col].dt.month == ctx_month)
            ]
        return matches

    # Try to find financial record in integrated decision register
    fin_rec = None
    if integrated_decision_df is not None and not integrated_decision_df.empty:
        if "approval_package_id" in integrated_decision_df.columns:
            matches = integrated_decision_df[integrated_decision_df["approval_package_id"] == pkg_id]
            # Apply context filter to matches
            matches = _filter_by_context(matches, "reporting_date")
            if matches.empty and dept_id and "department_id" in integrated_decision_df.columns:
                matches = integrated_decision_df[integrated_decision_df["department_id"] == dept_id]
                matches = _filter_by_context(matches, "reporting_date")
            if not matches.empty:
                fin_rec = matches.iloc[0]

    if fin_rec is None and financial_df is not None and not financial_df.empty:
        if "decision_package_id" in financial_df.columns:
            matches = financial_df[financial_df["decision_package_id"] == pkg_id]
            matches = _filter_by_context(matches, "reporting_date")
            # Only use dept_id fallback if no selected_context is provided,
            # to avoid cross-month/package matches
            if matches.empty and dept_id and not selected_context:
                matches = financial_df[financial_df["decision_package_id"].str.contains(dept_id, na=False)]
                matches = _filter_by_context(matches, "reporting_date")
            if not matches.empty:
                fin_rec = matches.iloc[0]

    if fin_rec is None:
        result["readiness_reasons"].append("No linked financial record found for the selected context.")
        result["missing_inputs"].append("Financial record not found for selected department and month")
        return result

    # Determine if quantified
    net_impact = fin_rec.get("net_financial_impact")
    # Also accept alternative column names used in different datasets
    cost = fin_rec.get("total_scenario_cost") if "total_scenario_cost" in fin_rec else None
    benefit = fin_rec.get("total_estimated_benefit") if "total_estimated_benefit" in fin_rec else None
    # Fallback: try to derive from other columns if direct columns are absent
    if cost is None and "central_estimate" in fin_rec:
        ce = fin_rec.get("central_estimate")
        if ce is not None and not pd.isna(ce):
            cost = ce
    if benefit is None and "upper_estimate" in fin_rec:
        ue = fin_rec.get("upper_estimate")
        if ue is not None and not pd.isna(ue):
            benefit = ue
    cost_completeness = str(fin_rec.get("cost_completeness_status", "")).strip()
    financial_readiness = str(fin_rec.get("financial_readiness", "")).strip()
    financial_confidence = str(fin_rec.get("financial_confidence", "")).strip()
    missing_flag = fin_rec.get("missing_financial_input_flag")
    review_reason = str(fin_rec.get("financial_review_reason", "")).strip()

    has_net = net_impact is not None and not pd.isna(net_impact)
    has_cost = cost is not None and not pd.isna(cost)
    has_benefit = benefit is not None and not pd.isna(benefit)
    is_not_quantified = (
        "not quantified" in cost_completeness.lower()
        or "not quantified" in financial_readiness.lower()
        or "monitoring only" in cost_completeness.lower()
        or "monitoring only" in financial_readiness.lower()
    )

    result["scenario_name"] = fin_rec.get("scenario_name", primary_pkg.get("dominant_kpi_name", ""))
    result["confidence"] = financial_confidence if financial_confidence else "Not Assessable"
    result["completeness"] = cost_completeness if cost_completeness else "Not Available"

    if has_net and not is_not_quantified:
        # State A: Quantified — reconcile net against benefit - cost
        result["display_state"] = "QUANTIFIED"
        result["cost"] = cost
        result["benefit"] = benefit
        result["net"] = net_impact

        # Reconciliation check
        reconciled = True
        reconciliation_note = ""
        if has_cost and has_benefit:
            try:
                computed_net = float(benefit) - float(cost)
                if abs(float(net_impact) - computed_net) > 0.01 * max(abs(computed_net), 1):
                    reconciled = False
                    reconciliation_note = (
                        f"Financial Reconciliation Required: governed net ({_compact_currency(net_impact)}) "
                        f"does not equal benefit ({_compact_currency(benefit)}) minus cost ({_compact_currency(cost)}). "
                        f"Computed net: {_compact_currency(computed_net)}."
                    )
            except Exception:
                reconciled = False
                reconciliation_note = "Financial Reconciliation Required: unable to verify net = benefit - cost."
        result["reconciled"] = reconciled

        if reconciled:
            has_all_three = has_cost and has_benefit
            if has_all_three:
                # Render signed horizontal bar chart when data is complete
                try:
                    fig = render_financial_impact_chart(cost, benefit, net_impact)
                    result["figure"] = fig
                except Exception:
                    result["figure"] = None
                result["html"] = (
                    f'<p style="margin-top:8px;font-size:12px;color:#6b7280;">'
                    f'Financial confidence: {financial_confidence} | Completeness: {cost_completeness}</p>'
                )
            else:
                # Show itemised rows with Not Available for missing values
                def _fin_row(label, value, colour):
                    if value is None or pd.isna(value):
                        return (
                            f'<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;padding:4px 0;border-bottom:1px solid #f3f4f6;">'
                            f'<span style="font-size:12px;font-weight:600;">{label}</span>'
                            f'<span style="font-size:12px;color:#9ca3af;font-weight:500;">Not Available</span>'
                            f'</div>'
                        )
                    try:
                        v = float(value)
                        bar_width = min(abs(v) / max(abs(float(net_impact)), 1) * 100, 100)
                        bar_html = (
                            f'<div style="background:#eee;border-radius:4px;height:18px;position:relative;margin-top:4px;">'
                            f'  <div style="background:{colour};width:{bar_width:.1f}%;height:18px;border-radius:4px;"></div>'
                            f'  <span style="position:absolute;right:6px;top:1px;color:#374151;font-size:11px;font-weight:500;">{_compact_currency(value)}</span>'
                            f'</div>'
                        )
                    except Exception:
                        bar_html = f'<span style="font-size:12px;color:#9ca3af;font-weight:500;">Not Available</span>'
                    return (
                        f'<div style="margin-bottom:8px;">'
                        f'<div style="font-size:12px;font-weight:600;">{label}</div>'
                        f'{bar_html}'
                        f'</div>'
                    )
                try:
                    net_colour = "#e74c3c" if float(net_impact) < 0 else "#27ae60"
                except Exception:
                    net_colour = "#6b7280"
                result["html"] = (
                    '<div style="margin-top:8px;">'
                    + _fin_row("Estimated Intervention Cost", cost, "#e74c3c")
                    + _fin_row("Estimated Benefit / Avoided Exposure", benefit, "#27ae60")
                    + _fin_row("Estimated Net Financial Impact", net_impact, net_colour)
                    + '</div>'
                    f'<p style="margin-top:8px;font-size:12px;color:#6b7280;">Financial confidence: {financial_confidence} | Completeness: {cost_completeness}</p>'
                )
            result["text"] = (
                f"Net financial impact: {_compact_currency(net_impact)} "
                f"(Cost: {_compact_currency(cost)}, Benefit: {_compact_currency(benefit)})"
            )
        else:
            # Suppress net bar; show reconciliation warning with available cost/benefit inputs
            result["figure"] = None
            def _fin_row_plain(label, value):
                if value is None or pd.isna(value):
                    return f'<li>{label}: <span style="color:#9ca3af;">Not Available</span></li>'
                return f'<li>{label}: <strong>{_compact_currency(value)}</strong></li>'

            warn_html = (
                '<div style="padding:12px;border-radius:6px;background:#fff3cd;border-left:4px solid #f59e0b;margin-top:8px;">'
                f'<p style="margin:0 0 6px 0;font-weight:600;color:#856404;">⚠️ Financial Reconciliation Required</p>'
                f'<p style="margin:0 0 6px 0;font-size:12px;color:#856404;">{reconciliation_note}</p>'
                '<ul style="margin:0 0 6px 0;padding-left:18px;font-size:12px;">'
                + _fin_row_plain("Estimated Intervention Cost", cost)
                + _fin_row_plain("Estimated Benefit / Avoided Exposure", benefit)
                + _fin_row_plain("Estimated Net Financial Impact", net_impact)
                + '</ul>'
                f'<p style="margin:0;font-size:11px;color:#6b7280;">Financial confidence: {financial_confidence} | Completeness: {cost_completeness}</p>'
                '</div>'
            )
            result["html"] = warn_html
            result["text"] = reconciliation_note
    else:
        # State B: Readiness
        result["display_state"] = "READINESS"
        reasons = []
        if not has_net:
            reasons.append("Net financial impact not quantified.")
        if not has_cost:
            reasons.append("Intervention cost not available.")
        if not has_benefit:
            reasons.append("Estimated benefit not available.")
        if is_not_quantified:
            reasons.append(f"Package status: {cost_completeness or financial_readiness}")
        if missing_flag and str(missing_flag).lower() in ("true", "1", "yes"):
            reasons.append("Missing financial inputs flagged.")
        if review_reason:
            reasons.append(f"Review reason: {review_reason}")
        result["readiness_reasons"] = reasons
        result["missing_inputs"] = reasons

        readiness_html = (
            '<div style="padding:12px;border-radius:6px;background:#f9fafb;border-left:4px solid #f59e0b;">'
            '<p style="margin:0 0 6px 0;font-weight:600;">Estimated impact: Not Yet Quantified</p>'
            f'<p style="margin:0 0 6px 0;">Financial readiness: {financial_readiness or "Requires Intervention Scenario"}</p>'
            '<p style="margin:0 0 4px 0;font-weight:500;">Missing inputs:</p>'
            '<ul style="margin:0;padding-left:18px;font-size:12px;">'
            + "".join(f"<li>{r}</li>" for r in reasons)
            + '</ul>'
            '<p style="margin:8px 0 0 0;font-size:12px;color:#6b7280;">Next required step: Validate financial assumptions before management comparison.</p>'
            '</div>'
        )
        result["html"] = readiness_html
        result["text"] = "Financial impact not yet quantified. " + " ".join(reasons)

    return result


def _build_financial_block(financial_df, primary_pkg, selected_date, selected_context=None):
    """Build a legacy financial impact string for backward compatibility."""
    block = _build_financial_impact_block(primary_pkg, selected_date, financial_df, None, selected_context)
    return block["text"]


# ───────────────────────────────────────────────────────────────────────────
# COMPACT CURRENCY HELPER
# ───────────────────────────────────────────────────────────────────────────

def _compact_currency(value):
    """Compact currency for financial display (RM prefix)."""
    if value is None or pd.isna(value):
        return "Not Available"
    try:
        v = float(value)
        if abs(v) >= 1e6:
            return f"RM{v/1e6:,.2f}M"
        elif abs(v) >= 1e3:
            return f"RM{v/1e3:,.1f}K"
        else:
            return f"RM{v:,.0f}"
    except Exception:
        return str(value)


# ───────────────────────────────────────────────────────────────────────────
# SCENARIO COMPARISON BUILDER
# ───────────────────────────────────────────────────────────────────────────

def _build_scenario_comparison_block(
    scenarios, packages, selected_date, kpi_dept
):
    """Build a structured scenario comparison block with scenario-specific financial linkage.

    Returns a dict with:
      - has_quantified (bool)
      - scenarios (list[dict]) — up to 3 valid scenarios
      - explanation (str) — fallback text when no valid scenarios
      - next_step (str)
    """
    result = {
        "has_quantified": False,
        "scenarios": [],
        "explanation": "",
        "next_step": "",
    }

    if scenarios is None or scenarios.empty:
        result["explanation"] = (
            "Scenario comparison requires scenario-specific financial linkage.\n"
            "Next step: link each scenario to its financial estimate using scenario_id and decision_package_id."
        )
        result["next_step"] = "link each scenario to its financial estimate using scenario_id and decision_package_id"
        return result

    valid_scenarios = []
    scenario_fields = [
        ("Baseline", "baseline_summary"),
        ("Conservative", "conservative_summary"),
        ("Expected", "expected_summary"),
        ("Higher Intensity", "higher_intensity_summary"),
    ]

    for _, row in scenarios.iterrows():
        confidence = row.get("confidence", "")
        for label, col in scenario_fields:
            summary = row.get(col)
            if summary and str(summary).strip():
                # Look up scenario-specific financial fields
                cost = row.get("scenario_cost")
                benefit = row.get("scenario_benefit")
                net = row.get("scenario_net_impact")
                # Fallback to prefixed columns if available
                if cost is None or pd.isna(cost):
                    cost = row.get(f"{col.replace('_summary', '')}_cost")
                if benefit is None or pd.isna(benefit):
                    benefit = row.get(f"{col.replace('_summary', '')}_benefit")
                if net is None or pd.isna(net):
                    net = row.get(f"{col.replace('_summary', '')}_net")
                # Never expose nan
                if cost is not None and pd.isna(cost):
                    cost = None
                if benefit is not None and pd.isna(benefit):
                    benefit = None
                if net is not None and pd.isna(net):
                    net = None
                # If no scenario-specific financials at all, mark incomplete
                has_scenario_financials = any(v is not None for v in [cost, benefit, net])
                if not has_scenario_financials:
                    # Do not fabricate — this scenario lacks linkage
                    continue
                valid_scenarios.append({
                    "label": label,
                    "summary": str(summary).strip(),
                    "cost": cost,
                    "benefit": benefit,
                    "net": net,
                    "confidence": str(confidence).strip() if confidence else "",
                })

    # De-duplicate by label and cap at 3
    seen = set()
    deduped = []
    for s in valid_scenarios:
        if s["label"] not in seen:
            seen.add(s["label"])
            deduped.append(s)
    valid_scenarios = deduped[:3]

    if valid_scenarios:
        result["has_quantified"] = True
        result["scenarios"] = valid_scenarios
        result["explanation"] = ""
        result["next_step"] = ""
    else:
        result["explanation"] = (
            "Scenario comparison requires scenario-specific financial linkage.\n"
            "No quantified scenario financials were found for the selected package."
        )
        result["next_step"] = "link each scenario to its financial estimate using scenario_id and decision_package_id"

    return result


# ───────────────────────────────────────────────────────────────────────────
# SITUATION BUILDER
# ───────────────────────────────────────────────────────────────────────────

def _build_situation_content(
    situation_type, scenario_data, kpi_daily, filtered_risk, selected_date, kpi_dept
):
    """Build a situation analysis block."""
    if situation_type == "Informed":
        return "Informed scenario: baseline operations with no major interventions."
    elif situation_type == "Optimised":
        return "Optimised scenario: targeted improvements in staffing and patient flow."
    elif situation_type == "Compromised":
        return "Compromised scenario: reduced capacity with increased risk of breaches."
    else:
        return f"{situation_type} scenario: custom configuration."


def _build_situation_builders():
    """Return situation builder configurations."""
    return [
        {"type": "Informed", "label": "Current State"},
        {"type": "Optimised", "label": "Optimised"},
        {"type": "Compromised", "label": "Compromised"},
    ]


def _build_situation_kpis(situation_type, kpi_data, kpi_dept):
    """Build KPI data for a situation (all six KPIs)."""
    if kpi_data is None or kpi_data.empty:
        return []

    kpis = []
    for kpi_id in ["kpi_001", "kpi_002", "kpi_003", "kpi_004", "kpi_005", "kpi_006"]:
        mask = (kpi_data["kpi_id"] == kpi_id) & (kpi_data["department_id"] == kpi_dept)
        rows = kpi_data[mask]
        if not rows.empty:
            row = rows.iloc[-1]
            kpis.append({
                "kpi_id": kpi_id,
                "kpi_name": row.get("kpi_name", kpi_id),
                "value": row.get("kpi_value", None),
                "unit": row.get("kpi_unit", ""),
            })
    return kpis


def _build_situation_narrative(situation_type, kpi_data, kpi_dept):
    """Build a narrative for a situation."""
    if situation_type == "Informed":
        return "Current operations with no major interventions."
    elif situation_type == "Optimised":
        return "Optimised operations with targeted improvements."
    elif situation_type == "Compromised":
        return "Compromised operations with reduced capacity."
    return f"{situation_type} operations."


# ───────────────────────────────────────────────────────────────────────────
# MAIN PAGE STATE BUILDER
# ───────────────────────────────────────────────────────────────────────────

def build_executive_page_state(
    data,
    filters,
):
    """
    Build the complete page state for the Executive Overview.

    KPI statuses are now evaluated independently from actual values and thresholds,
    decoupled from package-level risk.
    """
    global _log

    dept_name = filters.get("department_name", "All Departments")
    kpi_dept = filters.get("department_id", "ALL")
    hospital_id = filters.get("hospital_id", "HOSP-001")
    year = int(filters.get("year", 2025))
    month = int(filters.get("month", 1))
    selected_date = filters.get("reporting_date")

    # Extract data from dict with backward-compatible key fallbacks
    kpi_daily = data.get("kpi_daily", pd.DataFrame()) if data else pd.DataFrame()
    risk_alert = data.get("risk_alert", pd.DataFrame()) if data else pd.DataFrame()
    if data:
        financial = data.get("financial_impact", pd.DataFrame())
        if financial.empty:
            financial = data.get("financial", pd.DataFrame())
        integrated_decision = data.get("integrated_decision", pd.DataFrame())
        if integrated_decision.empty:
            integrated_decision = data.get("situations", pd.DataFrame())
        scenarios = data.get("scenario_comparison", pd.DataFrame())
        if scenarios.empty:
            scenarios = data.get("scenarios", pd.DataFrame())
        forecast_df = data.get("forecast_monthly", pd.DataFrame())
        warning_df = data.get("forecast_warnings", pd.DataFrame())
        eligibility_df = data.get("forecast_eligibility", pd.DataFrame())
        method_df = data.get("forecast_method", pd.DataFrame())
    else:
        financial = pd.DataFrame()
        integrated_decision = pd.DataFrame()
        scenarios = pd.DataFrame()
        forecast_df = pd.DataFrame()
        warning_df = pd.DataFrame()
        eligibility_df = pd.DataFrame()
        method_df = pd.DataFrame()

    # Period classification (ACTUAL vs FORECAST)
    period_type = get_period_type(year, month)

    # Load threshold configuration
    threshold_cfg = load_kpi_threshold_config()

    # Build all six KPI cards with value-based status (uses selected month)
    all_kpi_cards = _build_all_kpi_cards(
        kpi_daily, kpi_dept, selected_date, None, None, threshold_cfg,
        hospital_id=hospital_id, year=year, month=month,
        forecast_df=forecast_df,
        warning_df=warning_df,
        eligibility_df=eligibility_df,
    )
    primary_kpi_cards, supporting_kpi_cards = _split_primary_and_supporting(all_kpi_cards)

    # Evaluate all 6 KPIs for dominant issue selection using the same card data
    # This ensures the dominant issue reflects the exact values shown on the cards
    STATUS_TEXT_TO_STATUS = {
        "Critical": "Red",
        "Warning": "Amber",
        "Acceptable": "Green",
        "Monitoring": "Monitoring",
        "Not Assessable": "Monitoring",
        "Insufficient Data": "Monitoring",
    }
    all_kpi_statuses = {}
    for card in all_kpi_cards:
        kpi_id = card.get("kpi_id")
        if not kpi_id:
            continue
        status_text = card.get("threshold_status", "Monitoring")
        raw_status = STATUS_TEXT_TO_STATUS.get(status_text, "Monitoring")
        all_kpi_statuses[kpi_id] = {
            "kpi_id": kpi_id,
            "kpi_name": card.get("kpi_name", ""),
            "status": raw_status,
            "severity_score": card.get("severity_score", 0),
        }

    # Select dominant issue using value-based evaluation (not package inheritance)
    dominant_result = select_dominant_issue(all_kpi_statuses)
    dominant_kpi_id = dominant_result["dominant_kpi_id"]
    dominant_kpi_name = dominant_result["dominant_kpi_name"]
    dominant_status = dominant_result["dominant_status"]

    # Derive operational status from the selected-month KPI cards
    operational_status = _derive_operational_status_from_cards(primary_kpi_cards)
    if operational_status == "PRIORITY MANAGEMENT REVIEW":
        risk_tier = "High"
    elif operational_status == "MANAGEMENT REVIEW REQUIRED":
        risk_tier = "Medium"
    else:
        risk_tier = "Low"

    # Select primary package from risk_alert filtered by selected context
    primary_pkg = None
    risk_alert_for_selection = None
    DEPT_CODE_TO_NAME = {
        "DEPT-ED": "Emergency Department",
        "DEPT-ICU": "Intensive Care Unit",
        "DEPT-MED": "Medical Ward",
        "DEPT-ADM": "Admissions",
        "DEPT-DIAG": "Diagnostics",
        "DEPT-OPC": "Outpatient Clinic",
        "DEPT-SUR": "Surgery",
        "DEPT-PE": "Patient Experience",
    }
    if risk_alert is not None and not risk_alert.empty:
        risk_alert_for_selection = risk_alert.copy()
        # Filter by department (try both code and name columns)
        if kpi_dept != "ALL":
            dept_name = DEPT_CODE_TO_NAME.get(kpi_dept, kpi_dept)
            dept_matches = None
            if "department_id" in risk_alert_for_selection.columns:
                dept_matches = risk_alert_for_selection[risk_alert_for_selection["department_id"] == kpi_dept]
            if (dept_matches is None or dept_matches.empty) and "affected_department" in risk_alert_for_selection.columns:
                dept_matches = risk_alert_for_selection[risk_alert_for_selection["affected_department"] == dept_name]
            if dept_matches is not None and not dept_matches.empty:
                risk_alert_for_selection = dept_matches
            else:
                # No department match found — do not silently fallback; keep empty
                risk_alert_for_selection = risk_alert_for_selection.iloc[0:0]
        # Filter by selected year and month
        if "reporting_date" in risk_alert_for_selection.columns and not risk_alert_for_selection.empty:
            risk_alert_for_selection["ra_year"] = pd.to_datetime(risk_alert_for_selection["reporting_date"], errors="coerce").dt.year
            risk_alert_for_selection["ra_month"] = pd.to_datetime(risk_alert_for_selection["reporting_date"], errors="coerce").dt.month
            risk_alert_for_selection = risk_alert_for_selection[
                (risk_alert_for_selection["ra_year"] == year) &
                (risk_alert_for_selection["ra_month"] == month)
            ]
        if not risk_alert_for_selection.empty:
            primary_pkg = select_primary_package(risk_alert_for_selection)

    pkg_date = None
    if primary_pkg is not None and "reporting_date" in primary_pkg:
        pkg_date = primary_pkg["reporting_date"]

    # Build operational pressure story using primary cards only
    operational_story = _build_operational_pressure_story(
        primary_kpi_cards, primary_pkg, threshold_cfg
    )

    # Management action tailored to the actual dominant KPI
    management_action = _get_kpi_specific_management_action(dominant_kpi_id, dominant_status)
    if not dominant_kpi_id:
        management_action = "No material operational breach. Continue routine monitoring."

    # Forecast context: capability notice + dominant warning + suggested action
    forecast_capability = get_forecast_capability_notice()
    dominant_forecast_warning = {}
    if period_type == "FORECAST" and kpi_dept != "ALL" and dominant_kpi_id:
        dominant_forecast_warning = lookup_forecast_warning(
            warning_df, hospital_id, kpi_dept, dominant_kpi_id, year, month
        )

    # Canonical selected context object
    selected_context = {
        "hospital_id": hospital_id,
        "hospital_name": hospital_id,
        "department_id": kpi_dept,
        "department_name": dept_name,
        "selected_year": year,
        "selected_month": month,
        "selected_period_start": selected_date,
        "selected_period_end": selected_date,
        "period_type": "monthly",
        "relevant_kpi_ids": ["kpi_001", "kpi_002", "kpi_003", "kpi_004", "kpi_005", "kpi_006"],
        "scenario_id": None,
    }

    # Build financial impact block with State A/B logic
    financial_impact_block = _build_financial_impact_block(
        primary_pkg, selected_date, financial, integrated_decision, selected_context
    )
    financial_block_text = financial_impact_block.get("text", "")

    # Narrative that reflects the actual dominant issue (or stable state)
    narrative = _build_executive_narrative_block(
        dept_name, selected_date, dominant_kpi_name, dominant_kpi_id, dominant_status,
        primary_kpi_cards, financial_block_text, selected_date
    )

    financial_narrative = (
        f"Financial impact as of {selected_date}: "
        f"{financial_block_text}."
    )

    scenario_comparison = _build_scenario_comparison_block(
        scenarios, risk_alert, selected_date, kpi_dept
    )
    # Ensure scenario_comparison is a dict (new structured format)
    if isinstance(scenario_comparison, str):
        scenario_comparison = {
            "has_quantified": False,
            "scenarios": [],
            "explanation": scenario_comparison,
            "next_step": "",
        }

    situation_builders = _build_situation_builders()
    situation_kpis = _build_situation_kpis("Informed", kpi_daily, kpi_dept)
    situation_narrative = _build_situation_narrative("Informed", kpi_daily, kpi_dept)

    header = _build_5_piece_header(dept_name, selected_date, primary_pkg, risk_alert)

    # Backward-compatible state mapping for the page
    return {
        "header": header,
        "three_kpi_cards": primary_kpi_cards,
        "primary_kpi_cards": primary_kpi_cards,
        "supporting_kpi_cards": supporting_kpi_cards,
        "all_kpi_cards": all_kpi_cards,
        "all_kpi_statuses": all_kpi_statuses,
        "dominant_kpi_id": dominant_kpi_id,
        "dominant_kpi_name": dominant_kpi_name,
        "dominant_status": dominant_status,
        "operational_status": operational_status,
        "risk_tier": risk_tier,
        "operational_story": operational_story,
        "management_action": management_action,
        "narrative": narrative,
        "financial_block": financial_block_text,
        "financial_impact_block": financial_impact_block,
        "financial_narrative": financial_narrative,
        "scenario_comparison": scenario_comparison,
        "situation_builders": situation_builders,
        "situation_kpis": situation_kpis,
        "situation_narrative": situation_narrative,
        "primary_package": primary_pkg,
        "risk_alert": risk_alert,
        "selected_date": selected_date,
        "department_name": dept_name,
        "department_id": kpi_dept,
        "threshold_config": threshold_cfg,
        "issue_ranking": dominant_result.get("ranking", []),
        # Forecast context (Phase 3B-FI)
        "period_type": period_type,
        "forecast_capability": forecast_capability,
        "dominant_forecast_warning": dominant_forecast_warning,
        "forecast_monthly": forecast_df,
        "forecast_warnings": warning_df,
        "forecast_eligibility": eligibility_df,
        "forecast_method": method_df,
        # Legacy keys for backward compatibility
        "executive_narrative": narrative,
        "pressure_story": operational_story,
        "management_review": {
            "primary_permitted_action": management_action,
            "executive_headline": "Management Review" if dominant_kpi_id else "Routine Monitoring",
            "issue_summary": dominant_kpi_name if dominant_kpi_id else "No issues identified",
            "readiness": "Ready" if dominant_kpi_id else "Routine",
            "outstanding_condition": "None" if not dominant_kpi_id else "Requires attention",
        },
        "financial": {
            "net": financial_impact_block.get("net"),
            "cost": financial_impact_block.get("cost"),
            "benefit": financial_impact_block.get("benefit"),
            "display_confidence": financial_impact_block.get("confidence", "Not Assessable"),
        },
        "scenario_data": scenario_comparison,
        "selected_context": selected_context,
        "supporting_detail": {},
        "urgency": "Low" if not dominant_kpi_id else "High" if dominant_status == "Red" else "Medium",
        "financial_exposure_display": financial_impact_block.get("text", "N/A"),
    }
